debug= false

[steamgrid_db]
auth_key = "Write your authentication key between these quotes"
enabled = true
prefer_animated = false
safe_download = true

[origin]
enabled = true

[gog]
enabled = true
create_symlinks = true

[epic_games]
enabled = true
create_symlinks = true

[uplay]
enabled = true

[legendary]
enabled = true

[itch]
enabled = true
create_symlinks = true

[lutris]
enabled = true

[steam]